"""A2L (ASAP2) calibration file generator.

Generates ASAP2-compliant A2L files from A2LData structures. Output is
compatible with ETAS INCA, Vector CANape, and other calibration tools.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from core.generators.base import BaseGenerator, GenerateResult
from core.parsers.a2l_parser import A2LCharacteristic, A2LCompuMethod, A2LData, A2LMeasurement


class A2LGenerator(BaseGenerator):
    """Generate ASAP2 A2L calibration files from A2LData."""

    def __init__(self, template_dir: Path | None = None):
        # A2L generation does not use Jinja2 templates; pass a dummy path.
        if template_dir is None:
            template_dir = Path(__file__).parent
        super().__init__(template_dir)

    # ── Public API ────────────────────────────────────────────────────────

    def generate(self, data: A2LData, output_path: Path) -> GenerateResult:
        """Write an A2L file to *output_path* (file path, not directory).

        Returns a GenerateResult with the written file path on success.
        """
        errors: list[str] = []
        try:
            content = self.generate_string(data)
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            self._write_file(output_path, content)
            return GenerateResult(success=True, output_files=[output_path])
        except (OSError, ValueError) as exc:
            errors.append(str(exc))
            return GenerateResult(success=False, errors=errors)

    def generate_string(self, data: A2LData) -> str:
        """Return the full A2L text for *data*."""
        lines: list[str] = []
        self._emit_project_open(lines, data)
        self._emit_module(lines, data)
        self._emit_project_close(lines)
        return "\n".join(lines) + "\n"

    # ── Project / Module ──────────────────────────────────────────────────

    def _emit_project_open(self, lines: list[str], data: A2LData) -> None:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        project_name = self._derive_project_name(data)
        lines.append(f'/* Auto-generated by VCU DevKit — {ts} */')
        lines.append(f'/* Source: {data.source_path} */')
        lines.append(f'/* DO NOT EDIT MANUALLY */')
        lines.append("")
        lines.append(f'/begin PROJECT {project_name} "{project_name}"')
        lines.append(f'  /begin HEADER "VCU DevKit Export"')
        lines.append(f'    VERSION "1.0"')
        lines.append(f'  /end HEADER')

    def _emit_project_close(self, lines: list[str]) -> None:
        lines.append("/end PROJECT")
        lines.append("")

    def _emit_module(self, lines: list[str], data: A2LData) -> None:
        project_name = self._derive_project_name(data)
        lines.append(f'  /begin MODULE {project_name}_Module "{project_name} Module"')
        self._emit_compu_methods(lines, data.compu_methods)
        self._emit_characteristics(lines, data.characteristics)
        self._emit_measurements(lines, data.measurements)
        lines.append(f'  /end MODULE')

    # ── COMPU_METHOD ──────────────────────────────────────────────────────

    def _emit_compu_methods(self, lines: list[str], methods: list[A2LCompuMethod]) -> None:
        if not methods:
            return
        for cm in methods:
            fmt = cm.format_string or "%8.4"
            unit = cm.unit or ""
            if cm.conversion_type == "IDENTICAL":
                lines.append(f'    /begin COMPU_METHOD {cm.name} "{cm.description}" IDENTICAL "{fmt}" "{unit}"')
            elif cm.conversion_type == "LINEAR":
                coeffs = self._linear_coeffs(cm)
                lines.append(f'    /begin COMPU_METHOD {cm.name} "{cm.description}" LINEAR "{fmt}" "{unit}"')
                lines.append(f'      COEFFS {self._fmt_coeffs(coeffs)}')
            elif cm.conversion_type == "RAT_FUNC":
                coeffs = cm.coeffs if cm.coeffs else [0, 1, 0, 0, 0, 0]
                lines.append(f'    /begin COMPU_METHOD {cm.name} "{cm.description}" RAT_FUNC "{fmt}" "{unit}"')
                lines.append(f'      COEFFS {self._fmt_coeffs(coeffs)}')
            elif cm.conversion_type == "FORM":
                lines.append(f'    /begin COMPU_METHOD {cm.name} "{cm.description}" FORM "{fmt}" "{unit}"')
                if cm.formula:
                    lines.append(f'      FORMULA "{cm.formula}"')
            else:
                # TAB_INTP, TAB_NOINTP, or unknown — emit raw type
                lines.append(f'    /begin COMPU_METHOD {cm.name} "{cm.description}" {cm.conversion_type} "{fmt}" "{unit}"')
                if cm.coeffs:
                    lines.append(f'      COEFFS {self._fmt_coeffs(cm.coeffs)}')
            lines.append(f'    /end COMPU_METHOD')

    # ── CHARACTERISTIC ────────────────────────────────────────────────────

    def _emit_characteristics(self, lines: list[str], chars: list[A2LCharacteristic]) -> None:
        if not chars:
            return
        for c in chars:
            long_id = c.long_identifier or c.name
            char_type = c.type or "VALUE"
            addr = self._fmt_address(c.address)
            layout = c.record_layout or "Default_RL"
            max_diff = self._fmt_num(c.max_diff)
            conv = c.conversion or "CM_noConversion"
            lower = self._fmt_num(c.lower_limit)
            upper = self._fmt_num(c.upper_limit)

            lines.append(f'    /begin CHARACTERISTIC {c.name} "{long_id}" {char_type} {addr} {layout} {max_diff} {conv} {lower} {upper}')
            if c.unit:
                lines.append(f'      UNIT "{c.unit}"')
            if c.description and c.description != long_id:
                lines.append(f'      LONG-NAME "{c.description}"')
            lines.append(f'    /end CHARACTERISTIC')

    # ── MEASUREMENT ───────────────────────────────────────────────────────

    def _emit_measurements(self, lines: list[str], measurements: list[A2LMeasurement]) -> None:
        if not measurements:
            return
        for m in measurements:
            long_id = m.long_identifier or m.name
            dtype = m.data_type or "UBYTE"
            conv = m.conversion or "CM_noConversion"
            resolution = m.resolution if m.resolution else 1
            accuracy = self._fmt_num(m.accuracy)
            lower = self._fmt_num(m.lower_limit)
            upper = self._fmt_num(m.upper_limit)

            lines.append(f'    /begin MEASUREMENT {m.name} "{long_id}" {dtype} {conv} {resolution} {accuracy} {lower} {upper}')
            if m.unit:
                lines.append(f'      UNIT "{m.unit}"')
            if m.description and m.description != long_id:
                lines.append(f'      LONG-NAME "{m.description}"')
            lines.append(f'    /end MEASUREMENT')

    # ── Helpers ───────────────────────────────────────────────────────────

    @staticmethod
    def _derive_project_name(data: A2LData) -> str:
        """Derive a project name from source path or default."""
        if data.source_path and data.source_path != "<string>":
            stem = Path(data.source_path).stem
            if stem:
                return stem
        return "VCU_Project"

    @staticmethod
    def _fmt_address(addr: int) -> str:
        return f"0x{addr:08X}" if addr else "0x00000000"

    @staticmethod
    def _fmt_num(value: float) -> str:
        """Format a numeric value, using int representation when possible."""
        if value == int(value):
            return str(int(value))
        return f"{value:.6g}"

    @staticmethod
    def _fmt_coeffs(coeffs: list[float]) -> str:
        """Format coefficient list as space-separated integers/floats."""
        parts: list[str] = []
        for c in coeffs:
            if c == int(c):
                parts.append(str(int(c)))
            else:
                parts.append(f"{c:.6g}")
        return " ".join(parts)

    @staticmethod
    def _linear_coeffs(cm: A2LCompuMethod) -> list[float]:
        """Return COEFFS for a LINEAR compu method.

        ASAP2 LINEAR uses COEFFS a b c d e f where the linear equation is
        y = (a*x^2 + b*x + c) / (d*x^2 + e*x + f).
        For a simple linear conversion y = factor * x + offset we set
        a=0, b=factor, c=offset, d=0, e=1, f=0.
        """
        if cm.coeffs and len(cm.coeffs) >= 6:
            return cm.coeffs[:6]
        # Default identity
        return [0, 1, 0, 0, 0, 0]
