"""CAN Pack/Unpack C code generator — produces real, compilable logic."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from core.generators.base import BaseGenerator, GenerateResult
from core.parsers.dbc_parser import DBCData, MessageDef, SignalDef


class CANCodeGenerator(BaseGenerator):
    """Generate C pack/unpack code from DBC data."""

    def __init__(self, template_dir: Path | None = None):
        if template_dir is None:
            template_dir = Path(__file__).parent.parent / "templates" / "c"
        super().__init__(template_dir)

    def generate(self, data: DBCData, output_dir: Path) -> GenerateResult:
        output_dir = Path(output_dir)
        output_files: list[Path] = []
        errors: list[str] = []
        try:
            h_content = self._generate_header(data)
            output_files.append(self._write_file(output_dir / "can_pack.h", h_content))

            sig_content = self._generate_signal_mapping(data)
            output_files.append(self._write_file(output_dir / "can_signals.h", sig_content))

            msg_content = self._generate_message_ids(data)
            output_files.append(self._write_file(output_dir / "can_messages.h", msg_content))

            return GenerateResult(success=True, output_files=output_files)
        except (OSError, ValueError) as exc:
            errors.append(str(exc))
            return GenerateResult(success=False, output_files=output_files, errors=errors)

    # ── Main header generator ────────────────────────────────────────────

    def _generate_header(self, data: DBCData) -> str:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            "/* Auto-generated by VCU DevKit - CAN Builder */",
            f"/* Source: {data.source_path} */",
            f"/* Date: {ts} */",
            "/* DO NOT EDIT MANUALLY */",
            "",
            "#ifndef CAN_PACK_H",
            "#define CAN_PACK_H",
            "",
            "#include <stdint.h>",
            "#include <string.h>",
            "",
        ]

        for msg in data.messages:
            fd_tag = " [CAN FD]" if msg.is_fd else ""
            lines.append(f"/* ========== {msg.name} (0x{msg.id:03X}) — DLC={msg.dlc}{fd_tag} ========== */")
            lines.append(f"#define CAN_MSG_{msg.name}  0x{msg.id:04X}u")
            lines.append(f"#define CAN_DLC_{msg.name}  {msg.dlc}u")
            if msg.is_fd:
                lines.append(f"#define CAN_IS_FD_{msg.name}  1")
            lines.append("")
            for sig in msg.signals:
                lines.extend(self._generate_signal_code(msg, sig))
            lines.append("")

        lines.append("#endif /* CAN_PACK_H */")
        lines.append("")
        return "\n".join(lines)

    # ── Per-signal code generation ───────────────────────────────────────

    def _generate_signal_code(self, msg: MessageDef, sig: SignalDef) -> list[str]:
        """Generate Pack/Unpack/ToPhys/FromPhys for one signal."""
        c_type = self._raw_c_type(sig)
        phys_type = "float"
        has_enum = bool(sig.value_descriptions)
        enum_name = f"{sig.name}_e"

        lines: list[str] = []
        lines.append(
            f"/* {sig.name}: start={sig.start_bit}, len={sig.bit_length}, "
            f"factor={sig.factor}, offset={sig.offset}, "
            f"range=[{sig.minimum},{sig.maximum}]"
            f"{' ' + sig.unit if sig.unit else ''} */"
        )

        # Enum typedef
        if has_enum:
            lines.append("typedef enum {")
            for val, desc in sorted(sig.value_descriptions.items(), key=lambda x: x[0]):
                lines.append(f"    {sig.name}_{self._safe_ident(desc)} = {val},")
            lines.append(f"}} {enum_name};")
            lines.append("")

        # Pack
        val_param = f"{enum_name} val" if has_enum else f"{c_type} val"
        lines.append(f"static inline void CAN_Pack_{sig.name}(uint8_t *buf, {val_param}) {{")
        if sig.bit_length == 1:
            lines.extend(self._pack_single_bit(sig))
        else:
            lines.extend(self._pack_raw(sig))
        lines.append("}")
        lines.append("")

        # Unpack
        ret_type = enum_name if has_enum else c_type
        lines.append(f"static inline {ret_type} CAN_Unpack_{sig.name}(const uint8_t *buf) {{")
        if sig.bit_length == 1:
            lines.extend(self._unpack_single_bit(sig))
        else:
            lines.extend(self._unpack_raw(sig, ret_type))
        lines.append("}")
        lines.append("")

        # ToPhysical (raw → physical)
        lines.append(f"static inline {phys_type} CAN_{sig.name}_ToPhysical({c_type} raw) {{")
        lines.append(
            f"    return ({phys_type})raw * ({phys_type}){self._f(sig.factor)}f + ({phys_type}){self._f(sig.offset)}f;"
        )
        lines.append("}")
        lines.append("")

        # FromPhysical (physical → raw)
        lines.append(f"static inline {c_type} CAN_{sig.name}_FromPhysical({phys_type} phys) {{")
        lines.append(
            f"    return ({c_type})((phys - ({phys_type}){self._f(sig.offset)}f) "
            f"/ ({phys_type}){self._f(sig.factor)}f);"
        )
        lines.append("}")
        lines.append("")
        return lines

    # ── Pack logic ───────────────────────────────────────────────────────

    def _pack_raw(self, sig: SignalDef) -> list[str]:
        """Generate pack code for multi-bit signals."""
        lines: list[str] = []
        if sig.byte_order == "little_endian":
            lines.append("    uint32_t raw = (uint32_t)val;")
            lines.append(f"    unsigned start_byte = {sig.start_bit // 8}u;")
            lines.append(f"    unsigned start_bit  = {sig.start_bit % 8}u;")
            lines.append(f"    unsigned remaining  = {sig.bit_length}u;")
            lines.append("    unsigned bit_pos    = 0;")
            lines.append("    while (remaining > 0) {")
            lines.append("        unsigned bits_in_byte = 8u - start_bit;")
            lines.append("        if (bits_in_byte > remaining) bits_in_byte = remaining;")
            lines.append("        uint8_t mask = (uint8_t)(((1u << bits_in_byte) - 1u) << start_bit);")
            lines.append("        uint8_t bits = (uint8_t)((raw >> bit_pos) << start_bit);")
            lines.append("        buf[start_byte] = (buf[start_byte] & ~mask) | (bits & mask);")
            lines.append("        bit_pos    += bits_in_byte;")
            lines.append("        remaining  -= bits_in_byte;")
            lines.append("        start_byte += 1u;")
            lines.append("        start_bit   = 0u;")
            lines.append("    }")
        else:
            # Big Endian (Motorola) — start_bit is MSB position
            msb_byte = sig.start_bit // 8
            msb_bit = sig.start_bit % 8
            lines.append("    uint32_t raw = (uint32_t)val;")
            lines.append(f"    unsigned cur_byte = {msb_byte}u;")
            lines.append(f"    unsigned cur_bit  = {msb_bit}u;")
            lines.append(f"    unsigned remaining = {sig.bit_length}u;")
            lines.append(f"    unsigned shift     = {sig.bit_length - 1}u;")
            lines.append("    while (remaining > 0) {")
            lines.append("        unsigned bits_here = cur_bit + 1;")
            lines.append("        if (bits_here > remaining) bits_here = remaining;")
            lines.append("        for (unsigned i = 0; i < bits_here; i++) {")
            lines.append("            uint8_t bit_val = (raw >> shift) & 1u;")
            lines.append("            uint8_t mask = 1u << (cur_bit - i);")
            lines.append("            buf[cur_byte] = (buf[cur_byte] & ~mask) | (bit_val << (cur_bit - i));")
            lines.append("            if (shift > 0) shift--;")
            lines.append("        }")
            lines.append("        remaining -= bits_here;")
            lines.append("        cur_byte += 1;")
            lines.append("        cur_bit   = 7;")
            lines.append("    }")
        return lines

    def _pack_single_bit(self, sig: SignalDef) -> list[str]:
        byte_idx = sig.start_bit // 8
        bit_idx = sig.start_bit % 8
        return [
            "    uint8_t bit_val = val ? 1u : 0u;",
            f"    buf[{byte_idx}] = (buf[{byte_idx}] & ~(1u << {bit_idx})) | (bit_val << {bit_idx});",
        ]

    # ── Unpack logic ─────────────────────────────────────────────────────

    def _unpack_raw(self, sig: SignalDef, ret_type: str) -> list[str]:
        lines: list[str] = []
        if sig.byte_order == "little_endian":
            lines.append("    uint32_t raw = 0;")
            lines.append(f"    unsigned start_byte = {sig.start_bit // 8}u;")
            lines.append(f"    unsigned start_bit  = {sig.start_bit % 8}u;")
            lines.append(f"    unsigned remaining  = {sig.bit_length}u;")
            lines.append("    unsigned bit_pos    = 0;")
            lines.append("    while (remaining > 0) {")
            lines.append("        unsigned bits_in_byte = 8u - start_bit;")
            lines.append("        if (bits_in_byte > remaining) bits_in_byte = remaining;")
            lines.append("        uint8_t mask = (uint8_t)(((1u << bits_in_byte) - 1u) << start_bit);")
            lines.append("        raw |= (uint32_t)((buf[start_byte] & mask) >> start_bit) << bit_pos;")
            lines.append("        bit_pos    += bits_in_byte;")
            lines.append("        remaining  -= bits_in_byte;")
            lines.append("        start_byte += 1u;")
            lines.append("        start_bit   = 0u;")
            lines.append("    }")
        else:
            msb_byte = sig.start_bit // 8
            msb_bit = sig.start_bit % 8
            lines.append("    uint32_t raw = 0;")
            lines.append(f"    unsigned cur_byte = {msb_byte}u;")
            lines.append(f"    unsigned cur_bit  = {msb_bit}u;")
            lines.append(f"    unsigned remaining = {sig.bit_length}u;")
            lines.append(f"    unsigned shift     = {sig.bit_length - 1}u;")
            lines.append("    while (remaining > 0) {")
            lines.append("        unsigned bits_here = cur_bit + 1;")
            lines.append("        if (bits_here > remaining) bits_here = remaining;")
            lines.append("        for (unsigned i = 0; i < bits_here; i++) {")
            lines.append("            uint8_t bit_val = (buf[cur_byte] >> (cur_bit - i)) & 1u;")
            lines.append("            raw |= (uint32_t)bit_val << shift;")
            lines.append("            if (shift > 0) shift--;")
            lines.append("        }")
            lines.append("        remaining -= bits_here;")
            lines.append("        cur_byte += 1;")
            lines.append("        cur_bit   = 7;")
            lines.append("    }")

        # Sign extension
        if sig.value_type == "signed" and sig.bit_length < 32:
            sign_bit = 1 << (sig.bit_length - 1)
            lines.append(f"    if (raw & 0x{sign_bit:X}u) raw |= ~0x{(1 << sig.bit_length) - 1:X}u;")
        lines.append(f"    return ({ret_type})raw;")
        return lines

    def _unpack_single_bit(self, sig: SignalDef) -> list[str]:
        byte_idx = sig.start_bit // 8
        bit_idx = sig.start_bit % 8
        return [
            f"    return (buf[{byte_idx}] >> {bit_idx}) & 1u ? 1 : 0;",
        ]

    # ── Signal mapping & message IDs ─────────────────────────────────────

    def _generate_signal_mapping(self, data: DBCData) -> str:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            "/* Auto-generated by VCU DevKit - CAN Builder */",
            f"/* Source: {data.source_path} */",
            f"/* Date: {ts} */",
            "/* DO NOT EDIT MANUALLY */",
            "",
            "#ifndef CAN_SIGNALS_H",
            "#define CAN_SIGNALS_H",
            "",
            '#include "can_pack.h"',
            "",
            "/* Physical value variables — write your application code here */",
            "",
        ]
        for msg in data.messages:
            lines.append(f"/* --- {msg.name} --- */")
            for sig in msg.signals:
                ctype = self._raw_c_type(sig)
                lines.append(f"extern {ctype} {sig.name};  /* {sig.unit} [{sig.minimum}..{sig.maximum}] */")
            lines.append("")
        lines.append("#endif /* CAN_SIGNALS_H */")
        lines.append("")
        return "\n".join(lines)

    def _generate_message_ids(self, data: DBCData) -> str:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            "/* Auto-generated by VCU DevKit - CAN Builder */",
            f"/* Source: {data.source_path} */",
            f"/* Date: {ts} */",
            "/* DO NOT EDIT MANUALLY */",
            "",
            "#ifndef CAN_MESSAGES_H",
            "#define CAN_MESSAGES_H",
            "",
        ]
        for msg in data.messages:
            lines.append(f"#define CAN_MSG_{msg.name:<30s} 0x{msg.id:04X}u  /* DLC={msg.dlc} sender={msg.sender} */")
        lines.append("")
        lines.append("#endif /* CAN_MESSAGES_H */")
        lines.append("")
        return "\n".join(lines)

    # ── Helpers ──────────────────────────────────────────────────────────

    @staticmethod
    def _raw_c_type(sig: SignalDef) -> str:
        if sig.value_type == "signed":
            if sig.bit_length <= 8:
                return "int8_t"
            if sig.bit_length <= 16:
                return "int16_t"
            if sig.bit_length <= 32:
                return "int32_t"
            return "int64_t"
        if sig.bit_length <= 8:
            return "uint8_t"
        if sig.bit_length <= 16:
            return "uint16_t"
        if sig.bit_length <= 32:
            return "uint32_t"
        return "uint64_t"

    @staticmethod
    def _safe_ident(name: str) -> str:
        return "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name)

    @staticmethod
    def _f(v: float) -> str:
        """Format float, strip trailing zeros."""
        s = f"{v:.10f}".rstrip("0").rstrip(".")
        return s if s else "0"
