"""CAPL code generator for CANoe network nodes."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from core.generators.base import BaseGenerator, GenerateResult
from core.parsers.dbc_parser import DBCData, MessageDef, SignalDef


class CAPLGenerator(BaseGenerator):
    """Generate CAPL (.can) code from DBC data for CANoe simulation."""

    def __init__(self, template_dir: Path | None = None):
        if template_dir is None:
            template_dir = Path(__file__).parent.parent / "templates" / "capl"
        super().__init__(template_dir)

    def generate(self, data: DBCData, output_dir: Path) -> GenerateResult:
        output_dir = Path(output_dir)
        errors: list[str] = []
        output_files: list[Path] = []
        try:
            content = self._generate_node(data)
            output_files.append(self._write_file(output_dir / "vcu_node.can", content))
            return GenerateResult(success=True, output_files=output_files)
        except Exception as exc:
            errors.append(str(exc))
            return GenerateResult(success=False, output_files=output_files, errors=errors)

    def _generate_node(self, data: DBCData) -> str:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            "/*@!Encoding:936*/",
            "/*",
            " * Auto-generated by VCU DevKit - CAN Builder",
            f" * Source: {data.source_path}",
            f" * Date: {ts}",
            " * DO NOT EDIT MANUALLY",
            " */",
            "",
            "includes",
            "{",
            "",
            "}",
            "",
            "/* ========== Global variables ========== */",
            "",
        ]

        # Variables for each signal
        for msg in data.messages:
            lines.append(f"/* --- {msg.name} (0x{msg.id:03X}) --- */")
            for sig in msg.signals:
                capl_type = self._capl_type(sig)
                capl_val = self._capl_default(sig)
                lines.append(f"{capl_type} {sig.name} = {capl_val};")
            lines.append("")

        # Timer declarations
        lines.append("/* ========== Timers ========== */")
        lines.append("msTimer cyclicTimer;")
        lines.append("")

        # on start
        lines.extend(
            [
                "/* ========== Initialization ========== */",
                "on start",
                "{",
                '  write("VCU node started");',
                "  setTimer(cyclicTimer, 10);  /* 10ms cycle */",
                "}",
                "",
            ]
        )

        # on timer
        lines.extend(
            [
                "/* ========== Cyclic task ========== */",
                "on timer cyclicTimer",
                "{",
                "  /* Update TX messages */",
            ]
        )
        for msg in data.messages:
            if msg.sender in ("VCU", ""):
                lines.extend(self._generate_tx_block(msg))
        lines.extend(
            [
                "",
                "  setTimer(this, 10);  /* Restart 10ms timer */",
                "}",
                "",
            ]
        )

        # on message handlers for RX messages
        lines.append("/* ========== Message reception handlers ========== */")
        for msg in data.messages:
            if msg.sender and msg.sender != "VCU":
                lines.extend(self._generate_rx_handler(msg))

        # Signal value callbacks
        lines.append("/* ========== Signal value callbacks ========== */")
        lines.append("/*")
        lines.append(" * Example: on signal VCU_Status.VCU_PowerMode")
        lines.append(" * {")
        lines.append(' *   write("PowerMode changed to %d", this);')
        lines.append(" * }")
        lines.append(" */")
        lines.append("")

        return "\n".join(lines)

    def _generate_tx_block(self, msg: MessageDef) -> list[str]:
        """Generate TX message packing code."""
        lines = [f"  /* --- {msg.name}{' (FD)' if msg.is_fd else ''} --- */"]
        lines.append("  {")
        fd_star = " *" if msg.is_fd else ""
        lines.append(f"    message{fd_star} {msg.id} msg_{msg.name};")
        for sig in msg.signals:
            lines.append(f"    msg_{msg.name}.{sig.name} = {sig.name};")
        lines.append(f"    output(msg_{msg.name});")
        lines.append("  }")
        lines.append("")
        return lines

    def _generate_rx_handler(self, msg: MessageDef) -> list[str]:
        """Generate on message handler for RX."""
        fd_tag = " (FD)" if msg.is_fd else ""
        lines = [f"/* --- {msg.name} (0x{msg.id:03X}){fd_tag} from {msg.sender} --- */"]
        lines.append(f"on message {msg.id}")
        lines.append("{")
        for sig in msg.signals:
            lines.append(f"  {sig.name} = this.{sig.name};")
        lines.append("}")
        lines.append("")
        return lines

    @staticmethod
    def _capl_type(sig: SignalDef) -> str:
        if sig.value_type == "signed":
            if sig.bit_length <= 8:
                return "byte"
            if sig.bit_length <= 16:
                return "int"
            return "long"
        if sig.bit_length <= 1:
            return "byte"
        if sig.bit_length <= 8:
            return "byte"
        if sig.bit_length <= 16:
            return "word"
        return "dword"

    @staticmethod
    def _capl_default(sig: SignalDef) -> str:
        if sig.value_type == "signed":
            return "0"
        if sig.bit_length <= 1:
            return "0"
        return "0"
