"""DCM (Data Calibration Method) file generator.

Generates DAMOS/CDM-format DCM files from calibration parameter data.
This matches the format used by ETAS INCA CDM exports, so output files
can be loaded directly into INCA.
"""

from __future__ import annotations

from pathlib import Path

from core.generators.base import BaseGenerator, GenerateResult


class DCMGenerator(BaseGenerator):
    """Generate DCM calibration data files in DAMOS/CDM format."""

    def __init__(self, template_dir: Path | None = None):
        if template_dir is None:
            template_dir = Path(__file__).parent
        super().__init__(template_dir)

    def generate(
        self,
        params: list[dict],
        output_path: Path,
        raw_blocks: dict[str, str] | None = None,
    ) -> GenerateResult:
        """Write a DCM file to output_path.

        params: list of dicts with keys: name, description, default_value,
                min_value, max_value, unit, block_type.
        raw_blocks: optional dict mapping param name to original DCM block text.
                    If present, non-FESTWERT params use their raw block text.
        """
        errors: list[str] = []
        try:
            content = self.generate_string(params, raw_blocks)
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            self._write_file(output_path, content)
            return GenerateResult(success=True, output_files=[output_path])
        except (OSError, ValueError) as exc:
            errors.append(str(exc))
            return GenerateResult(success=False, errors=errors)

    def generate_string(
        self,
        params: list[dict],
        raw_blocks: dict[str, str] | None = None,
    ) -> str:
        """Generate DCM content as a string in DAMOS/CDM format."""
        lines = [
            "* VCU Calibration Export",
            "* Generated by VCU-DevKit",
            "KONSERVIERUNG_FORMAT 2.0",
            "",
        ]

        for p in params:
            name = p.get("name", "")
            block_type = p.get("block_type", "")
            value = p.get("default_value")

            # Use raw block text for:
            # 1. Non-FESTWERT types (GRUPPENKENNFELD, FESTWERTEBLOCK, etc.)
            # 2. FESTWERT without numeric value (e.g. TEXT "true" params)
            has_raw = raw_blocks and name in raw_blocks
            use_raw = has_raw and (
                (block_type and block_type != "FESTWERT")
                or (block_type == "FESTWERT" and value is None)
            )
            if use_raw:
                lines.append(raw_blocks[name])
                lines.append("")
                continue

            # FESTWERT (scalar): rebuild from DB values
            desc = p.get("description", "")
            unit = p.get("unit", "")

            lines.append(f"FESTWERT {name}")
            if desc:
                lines.append(f'   LANGNAME "{desc}"')
            else:
                lines.append('   LANGNAME ""')
            lines.append(f'   EINHEIT_W "{unit or "-"}"')
            lines.append(f"   WERT {self._fmt_val(value)}")
            lines.append("END")
            lines.append("")

        return "\n".join(lines)

    @staticmethod
    def _fmt_val(value) -> str:
        """Format a numeric value for DCM output.

        Rounds to 10 significant digits to avoid float32→float64 artifacts
        while preserving full calibration precision.
        """
        if value is None:
            return "0"
        try:
            f = float(value)
            if f == 0:
                return "0"
            import math

            digits = 10 - int(math.floor(math.log10(abs(f)))) - 1
            f = round(f, max(digits, 0))
            s = f"{f:.10f}".rstrip("0").rstrip(".")
            return s
        except (ValueError, OverflowError):
            return str(value)
