"""J1939 C code generator — produces PGN/SPN/DTC C headers from J1939 data."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from core.generators.base import GenerateResult
from core.parsers.j1939_parser import J1939Data, J1939PGN, J1939SPN


class J1939CodeGenerator:
    """Generate J1939-specific C headers from J1939Data."""

    def __init__(self) -> None:
        pass

    def generate(self, data: J1939Data, output_dir: Path) -> GenerateResult:
        output_dir = Path(output_dir)
        output_files: list[Path] = []
        errors: list[str] = []
        try:
            j1939_h = self._generate_j1939_header(data)
            output_files.append(self._write_file(output_dir / "can_j1939.h", j1939_h))

            pgn_h = self._generate_pgn_header(data)
            output_files.append(self._write_file(output_dir / "j1939_pgn.h", pgn_h))

            spn_h = self._generate_spn_header(data)
            output_files.append(self._write_file(output_dir / "j1939_spn.h", spn_h))

            dtc_h = self._generate_dtc_header(data)
            output_files.append(self._write_file(output_dir / "j1939_dtc.h", dtc_h))

            return GenerateResult(success=True, output_files=output_files)
        except (OSError, ValueError) as exc:
            errors.append(str(exc))
            return GenerateResult(success=False, output_files=output_files, errors=errors)

    # ── Main J1939 header ──────────────────────────────────────────────────

    def _generate_j1939_header(self, data: J1939Data) -> str:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            "/* Auto-generated by VCU DevKit - J1939 CAN Builder */",
            f"/* Source: {data.dbc_data.source_path if data.dbc_data else 'unknown'} */",
            f"/* Date: {ts} */",
            "/* DO NOT EDIT MANUALLY */",
            "",
            "#ifndef CAN_J1939_H",
            "#define CAN_J1939_H",
            "",
            "#include <stdint.h>",
            "",
            '#include "j1939_pgn.h"',
            '#include "j1939_spn.h"',
            '#include "j1939_dtc.h"',
            "",
            "/* ── Source Addresses ─────────────────────────────────────── */",
            "",
        ]

        for node, sa in sorted(data.source_addresses.items(), key=lambda x: x[1]):
            safe = self._safe_ident(node)
            lines.append(f"#define J1939_SA_{safe:<30s} 0x{sa:02X}u")

        lines.append("")
        lines.append("/* ── Full CAN IDs (Priority 6, PDU2 format) ─────────────── */")
        lines.append("")

        for pgn in data.pgn_messages:
            safe = self._safe_ident(pgn.name)
            # Default priority 6 for most J1939 messages
            can_id = (6 << 26) | (pgn.pgn << 8) | pgn.source_address
            lines.append(
                f"#define J1939_ID_{safe:<30s} 0x{can_id:08X}u  "
                f"/* PGN=0x{pgn.pgn:04X} SA=0x{pgn.source_address:02X} */"
            )

        lines.append("")
        lines.append("#endif /* CAN_J1939_H */")
        lines.append("")
        return "\n".join(lines)

    # ── PGN header ─────────────────────────────────────────────────────────

    def _generate_pgn_header(self, data: J1939Data) -> str:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            "/* Auto-generated by VCU DevKit - J1939 PGN definitions */",
            f"/* Date: {ts} */",
            "",
            "#ifndef J1939_PGN_H",
            "#define J1939_PGN_H",
            "",
            "/* ── Parameter Group Numbers ─────────────────────────────── */",
            "",
        ]

        for pgn in sorted(data.pgn_messages, key=lambda p: p.pgn):
            safe = self._safe_ident(pgn.name)
            desc = f"  /* {pgn.description} */" if pgn.description else ""
            lines.append(f"#define J1939_PGN_{safe:<30s} 0x{pgn.pgn:04X}u{desc}")

        lines.append("")
        lines.append("#endif /* J1939_PGN_H */")
        lines.append("")
        return "\n".join(lines)

    # ── SPN header ─────────────────────────────────────────────────────────

    def _generate_spn_header(self, data: J1939Data) -> str:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            "/* Auto-generated by VCU DevKit - J1939 SPN definitions */",
            f"/* Date: {ts} */",
            "",
            "#ifndef J1939_SPN_H",
            "#define J1939_SPN_H",
            "",
            "#include <stdint.h>",
            "",
            "/* ── Suspect Parameter Numbers ───────────────────────────── */",
            "",
        ]

        for spn in sorted(data.spn_signals, key=lambda s: s.spn):
            if spn.spn == 0:
                continue  # Skip unknown SPNs
            safe = self._safe_ident(spn.name)
            unit_comment = f"  /* {spn.unit} */" if spn.unit else ""
            lines.append(f"#define J1939_SPN_{safe:<30s} {spn.spn}u{unit_comment}")

        lines.append("")

        # SPN struct typedef
        lines.append("/* SPN descriptor struct for runtime use */")
        lines.append("typedef struct {")
        lines.append("    uint16_t spn;")
        lines.append("    uint16_t pgn;")
        lines.append("    uint8_t  start_bit;")
        lines.append("    uint8_t  bit_length;")
        lines.append("    float    factor;")
        lines.append("    float    offset;")
        lines.append("    float    min_value;")
        lines.append("    float    max_value;")
        lines.append("    const char *name;")
        lines.append("    const char *unit;")
        lines.append("} J1939_SPN_Desc_t;")
        lines.append("")

        lines.append("#endif /* J1939_SPN_H */")
        lines.append("")
        return "\n".join(lines)

    # ── DTC header ─────────────────────────────────────────────────────────

    def _generate_dtc_header(self, data: J1939Data) -> str:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            "/* Auto-generated by VCU DevKit - J1939 DTC definitions */",
            f"/* Date: {ts} */",
            "",
            "#ifndef J1939_DTC_H",
            "#define J1939_DTC_H",
            "",
            "#include <stdint.h>",
            "",
            "/* ── J1939 DTC structure ─────────────────────────────────── */",
            "",
            "typedef struct {",
            "    uint16_t spn;         /* Suspect Parameter Number */",
            "    uint8_t  fmi;         /* Failure Mode Identifier */",
            "    uint8_t  occurrence;  /* Occurrence count */",
            "    uint8_t  status;      /* 0=active, 1=previously_active */",
            "} J1939_DTC_t;",
            "",
            "/* ── DM1/DM2 PGN definitions ─────────────────────────────── */",
            "",
            "#define J1939_PGN_DM1  0xFECAu  /* DM1 — Active DTCs */",
            "#define J1939_PGN_DM2  0xFECBu  /* DM2 — Previously Active DTCs */",
            "",
            "/* ── FMI (Failure Mode Identifier) codes ─────────────────── */",
            "",
            "#define J1939_FMI_HIGH_SEVERITY      0",
            "#define J1939_FMI_LOW_SEVERITY       1",
            "#define J1939_FMI_ERRATIC            2",
            "#define J1939_FMI_ABOVE_NORMAL_HI    3",
            "#define J1939_FMI_BELOW_NORMAL_LO    4",
            "#define J1939_FMI_NOT_RESPONDING     5",
            "#define J1939_FMI_ABOVE_NORMAL_LO    6",
            "#define J1939_FMI_BELOW_NORMAL_HI    7",
            "#define J1939_FMI_ABNORMAL_RATE_HI   8",
            "#define J1939_FMI_ABNORMAL_RATE_LO   9",
            "#define J1939_FMI_ABNORMAL_FREQ_HI  10",
            "#define J1939_FMI_ABNORMAL_FREQ_LO  11",
            "#define J1939_FMI_ABNORMAL_UPDATE    12",
            "#define J1939_FMI_ABNORMAL_RATIONALITY 13",
            "#define J1939_FMI_ABOVE_NORMAL_HI2  14",
            "#define J1939_FMI_BELOW_NORMAL_LO2  15",
            "#define J1939_FMI_ABNORMAL           16",
            "#define J1939_FMI_ABNORMAL_FREQ      17",
            "#define J1939_FMI_ABNORMAL_UPDATE2   18",
            "#define J1939_FMI_CALIBRATION        19",
            "#define J1939_FMI_SPECIAL_INSTRUCTIONS 20",
            "#define J1939_FMI_ABNORMAL_RATIONALITY2 21",
            "#define J1939_FMI_DATA_DRIFT_HI     22",
            "#define J1939_FMI_DATA_DRIFT_LO     23",
            "#define J1939_FMI_BAD_INTELLIGENT    24",
            "#define J1939_FMI_ABNORMAL_RATE      25",
            "#define J1939_FMI_ABNORMAL_UPDATE3   26",
            "#define J1939_FMI_ABNORMAL_RATIONALITY3 27",
            "#define J1939_FMI_ABNORMAL_RATIONALITY4 28",
            "#define J1939_FMI_ABNORMAL_RATIONALITY5 29",
            "#define J1939_FMI_ABNORMAL_RATIONALITY6 30",
            "#define J1939_FMI_CONDITION_EXISTS   31",
            "",
            "/* Helper: encode DTC to 4 bytes for DM1/DM2 transmission */",
            "static inline void J1939_EncodeDTC(uint8_t *buf, uint16_t spn, uint8_t fmi, uint8_t occ) {",
            "    buf[0] = (uint8_t)(spn & 0xFF);",
            "    buf[1] = (uint8_t)((spn >> 8) & 0xFF);",
            "    buf[2] = (uint8_t)(((spn >> 16) & 0x07) << 5) | (fmi & 0x1F);",
            "    buf[3] = (uint8_t)(occ & 0x7F);",
            "}",
            "",
            "/* Helper: decode 4-byte DTC from DM1/DM2 payload */",
            "static inline J1939_DTC_t J1939_DecodeDTC(const uint8_t *buf) {",
            "    J1939_DTC_t dtc;",
            "    dtc.spn = buf[0] | ((uint16_t)buf[1] << 8) | (((uint16_t)buf[2] >> 5) << 16);",
            "    dtc.fmi = buf[2] & 0x1F;",
            "    dtc.occurrence = buf[3] & 0x7F;",
            "    dtc.status = 0;",
            "    return dtc;",
            "}",
            "",
            "#endif /* J1939_DTC_H */",
            "",
        ]
        return "\n".join(lines)

    @staticmethod
    def _safe_ident(name: str) -> str:
        return "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name).upper()

    @staticmethod
    def _write_file(path: Path, content: str) -> Path:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return path
