"""AUTOSAR RTE header file generator — Rte_Type.h + Rte_<SWC>.h."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from core.generators.base import BaseGenerator, GenerateResult
from core.parsers.arxml_parser import (
    ARXMLData, SWCDef, PortDef, PortDirection,
    SenderReceiverInterface, ClientServerInterface,
    DataTypeDef,
)


# Encoding → C type mapping
_ENCODING_TO_C = {
    "uint8": "uint8",
    "uint16": "uint16",
    "uint32": "uint32",
    "uint64": "uint64",
    "sint8": "sint8",
    "sint16": "sint16",
    "sint32": "sint32",
    "sint64": "sint64",
    "float32": "float32",
    "float64": "float64",
    "boolean": "boolean",
}


class RTEGenerator(BaseGenerator):
    """Generate AUTOSAR RTE header files from ARXML data."""

    def __init__(self, template_dir: Path | None = None):
        if template_dir is None:
            template_dir = Path(__file__).parent.parent / "templates" / "rte"
        super().__init__(template_dir)

    def generate(self, data: ARXMLData, output_dir: Path) -> GenerateResult:
        output_dir = Path(output_dir)
        output_files: list[Path] = []
        errors: list[str] = []
        try:
            # Rte_Type.h
            type_content = self._generate_type_header(data)
            output_files.append(self._write_file(output_dir / "Rte_Type.h", type_content))

            # One Rte_<SWC>.h per SWC
            for swc in data.swcs:
                content = self._generate_swc_header(swc, data)
                safe_name = self._safe_ident(swc.name)
                output_files.append(self._write_file(output_dir / f"Rte_{safe_name}.h", content))

            return GenerateResult(success=True, output_files=output_files)
        except (OSError, ValueError) as exc:
            errors.append(str(exc))
            return GenerateResult(success=False, output_files=output_files, errors=errors)

    # ── Rte_Type.h ────────────────────────────────────────────────────────

    def _generate_type_header(self, data: ARXMLData) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            "/**",
            f" * Auto-generated by VCU DevKit — RTE Generator",
            f" * Source: {data.source_path}",
            f" * Date: {now}",
            " * DO NOT EDIT MANUALLY",
            " */",
            "",
            "#ifndef RTE_TYPE_H",
            "#define RTE_TYPE_H",
            "",
            "#include <stdint.h>",
            "",
            "/* ── Std_ReturnType ── */",
            "",
            "typedef uint8 Std_ReturnType;",
            "#define E_OK        ((Std_ReturnType)0u)",
            "#define E_NOT_OK    ((Std_ReturnType)1u)",
            "",
            "/* ── AUTOSAR base types ── */",
            "",
            "typedef uint8_t   uint8;",
            "typedef uint16_t  uint16;",
            "typedef uint32_t  uint32;",
            "typedef uint64_t  uint64;",
            "typedef int8_t    sint8;",
            "typedef int16_t   sint16;",
            "typedef int32_t   sint32;",
            "typedef int64_t   sint64;",
            "typedef float     float32;",
            "typedef double    float64;",
            "typedef uint8     boolean;",
            "#define TRUE        ((boolean)1u)",
            "#define FALSE       ((boolean)0u)",
            "",
        ]

        # Application data types
        if data.data_types:
            lines.append("/* ── Application data types ── */")
            lines.append("")
            for dt in data.data_types:
                c_type = _ENCODING_TO_C.get(dt.encoding, "uint8")
                lines.append(f"typedef {c_type} Rte_DT_{self._safe_ident(dt.name)};")
                if dt.min_value is not None or dt.max_value is not None:
                    mn = dt.min_value if dt.min_value is not None else 0
                    mx = dt.max_value if dt.max_value is not None else 0
                    lines.append(f"#define RTE_DT_{self._safe_ident(dt.name)}_MIN  ({mn})")
                    lines.append(f"#define RTE_DT_{self._safe_ident(dt.name)}_MAX  ({mx})")
            lines.append("")

        lines.append("#endif /* RTE_TYPE_H */")
        lines.append("")
        return "\n".join(lines)

    # ── Rte_<SWC>.h ───────────────────────────────────────────────────────

    def _generate_swc_header(self, swc: SWCDef, data: ARXMLData) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        safe = self._safe_ident(swc.name)
        guard = f"RTE_{safe.upper()}_H"

        lines = [
            "/**",
            f" * Auto-generated by VCU DevKit — RTE Generator",
            f" * SWC: {swc.name} ({swc.category})",
            f" * Date: {now}",
            " * DO NOT EDIT MANUALLY",
            " */",
            "",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            '#include "Rte_Type.h"',
            "",
        ]

        # Build interface lookup
        iface_map: dict[str, SenderReceiverInterface | ClientServerInterface] = {}
        for iface in data.interfaces:
            iface_map[iface.name] = iface

        # Port APIs
        if swc.ports:
            lines.append(f"/* ── Port APIs: {swc.name} ── */")
            lines.append("")
            for port in swc.ports:
                iface = iface_map.get(port.interface_ref)
                if isinstance(iface, SenderReceiverInterface):
                    lines.extend(self._generate_sr_port_api(swc.name, port, iface))
                elif isinstance(iface, ClientServerInterface):
                    lines.extend(self._generate_cs_port_api(swc.name, port, iface))
                else:
                    lines.append(f"/* Port {port.name}: interface '{port.interface_ref}' not resolved */")
                    lines.append("")

        # Runnable declarations
        if swc.runnables:
            lines.append(f"/* ── Runnable declarations: {swc.name} ── */")
            lines.append("")
            for r in swc.runnables:
                period = f"/* period: {r.period_ms}ms */" if r.period_ms else "/* event-triggered */"
                lines.append(f"void Rte_Run_{safe}_{self._safe_ident(r.name)}(void);  {period}")
            lines.append("")

        lines.append(f"#endif /* {guard} */")
        lines.append("")
        return "\n".join(lines)

    def _generate_sr_port_api(
        self, swc_name: str, port: PortDef, iface: SenderReceiverInterface
    ) -> list[str]:
        lines: list[str] = []
        safe_swc = self._safe_ident(swc_name)
        safe_port = self._safe_ident(port.name)

        for elem in iface.data_elements:
            c_type = self._resolve_type(elem.type_ref)
            safe_elem = self._safe_ident(elem.name)

            if port.direction == PortDirection.PROVIDED:
                # P-Port: provide write API
                lines.append(f"Std_ReturnType Rte_Write_{safe_swc}_{safe_port}_{safe_elem}({c_type} data);")
            else:
                # R-Port: provide read API
                lines.append(f"Std_ReturnType Rte_Read_{safe_swc}_{safe_port}_{safe_elem}({c_type}* data);")

        if lines:
            lines.insert(0, f"/* {port.direction.value.upper()}-Port: {port.name} ({port.interface_ref}) */")
        lines.append("")
        return lines

    def _generate_cs_port_api(
        self, swc_name: str, port: PortDef, iface: ClientServerInterface
    ) -> list[str]:
        lines: list[str] = []
        safe_swc = self._safe_ident(swc_name)
        safe_port = self._safe_ident(port.name)

        lines.append(f"/* CS-Port: {port.name} ({port.interface_ref}) */")
        for op in iface.operations:
            safe_op = self._safe_ident(op)
            if port.direction == PortDirection.PROVIDED:
                # P-Port: server provides the operation
                lines.append(f"Std_ReturnType Rte_Call_{safe_swc}_{safe_port}_{safe_op}(void);")
            else:
                # R-Port: client calls the operation
                lines.append(f"Std_ReturnType Rte_Call_{safe_swc}_{safe_port}_{safe_op}(void);")
        lines.append("")
        return lines

    def _resolve_type(self, type_ref: str) -> str:
        """Resolve a type reference to a C type."""
        # type_ref might be a path like "/Package/DataTypes/uint16"
        name = type_ref.rsplit("/", 1)[-1] if "/" in type_ref else type_ref
        c_type = _ENCODING_TO_C.get(name.lower())
        if c_type:
            return c_type
        return f"Rte_DT_{self._safe_ident(name)}"

    @staticmethod
    def _safe_ident(name: str) -> str:
        """Convert a name to a safe C identifier."""
        return "".join(c if c.isalnum() else "_" for c in name)
